### ISSUE TITLE
Start button for 21 day challenge

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#53]
As a User, I'd like to control when my 21 day challenge starts, so that the challenge 'clock' does not start before I am ready 

## Conditions of satisfaction

- [ ] Streak/clock control is inactive by default (does not count days ) 
- [ ] Streak/clock control does not start until user presses start button
- [ ] Streak/clock control screen has a start button, button disappears once pressed

## Tasks
- [ ] disable control by default
- [ ] display button
- [ ] putton press starts control counting and hides start button

## Notes and resources

* 

## Story writing guidelines - Can delete everything below here

*Acceptance criteria* are things that can be verified to show that this user story is satisfied.

* [“Advantages of the “As a user, I want” user story template.”](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)

### A good user story should be (I-N-V-E-S-T principle)

* _Independent_ (from other user stories, allowing to realize them in any order);
* _Negotiable_ (omit details that would freeze the story);
* _Valuable_ (implementation delivers an increment of functionality, observable by and useful to users);
* _Estimatable_ (developers should be able to estimate its size relative to other stories);
* _Sizable_ (implementation fits in one iteration – if it needs many to complete, it is an EPIC);
* _Testable_ (user must be able to check the conditions of satisfaction).
